In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
ds = pd.read_csv("data.csv")

In [3]:
ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 41.9 KB

In [4]:
ds["name"].unique()

<StringArray>
[  'Hyundai Santro Xing XO eRLX Euro III',
                'Mahindra Jeep CL550 MDI',
             'Maruti Suzuki Alto 800 Vxi',
 'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi',
                              'Ford Figo',
                            'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
         'Maruti Suzuki Alto K10 VXi AMT',
            'Skoda Fabia Classic 1.2 MPI',
 ...
         'Mercedes Benz C Class 200 K MT',
                            'Skoda Fabia',
  'Maruti Suzuki Alto 800 Select Variant',
             'Maruti Suzuki Ritz VXI ABS',
                       'tata zest 2017 f',
              'Tata Indica V2 DLE BS III',
                                     'Ta',
                    'Tata Zest XM Diesel',
               'Honda Amaze 1.2 E i VTEC',
              'Chevrolet Sail 1.2 LT ABS']
Length: 525, dtype: str

In [5]:
ds["year"].unique()

<StringArray>
['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016', '2010',
 '2017', '2008', '2011', '2019', '2009', '2005', '2000',  '...', '150k',
 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs', 'sale', '1995', 'ara)',
 '2002', 'SELL', '2001', 'tion', 'odel', '2 bs', 'arry',  'Eon', 'o...',
 'ture',  'emi',  'car', 'able',  'no.', 'd...', 'SALE', 'digo', 'sell',
 'd Ex', 'n...', 'e...', 'D...', ', Ac', 'go .', 'k...', 'o c4', 'zire',
 'cent', 'Sumo',  'cab', 't xe',  'EV2', 'r...', 'zest']
Length: 61, dtype: str

In [6]:
ds["year"] = pd.to_numeric(ds["year"],errors='coerce')
ds["year"].unique()

array([2007., 2006., 2018., 2014., 2015., 2012., 2013., 2016., 2010.,
       2017., 2008., 2011., 2019., 2009., 2005., 2000.,   nan, 2003.,
       2004., 1995., 2002., 2001.])

In [7]:
ds.dropna(subset=["year"],inplace=True)

In [8]:
ds["year"].unique()

array([2007., 2006., 2018., 2014., 2015., 2012., 2013., 2016., 2010.,
       2017., 2008., 2011., 2019., 2009., 2005., 2000., 2003., 2004.,
       1995., 2002., 2001.])

In [9]:
ds.info()

<class 'pandas.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    str
 1   company     842 non-null    str
 2   year        842 non-null    float64
 3   Price       842 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: float64(1), str(5)
memory usage: 46.0 KB

In [10]:
ds["Price"].unique()

<StringArray>
[       '80,000',      '4,25,000', 'Ask For Price',      '3,25,000',
      '5,75,000',      '1,75,000',      '1,90,000',      '8,30,000',
      '2,50,000',      '1,82,000',
 ...
        '42,000',      '1,89,000',      '1,62,000',        '35,999',
     '29,00,000',        '39,999',        '50,500',      '5,10,000',
      '8,60,000',      '5,00,001']
Length: 273, dtype: str

In [11]:
for i in ds.index:
    price = ds.loc[i,"Price"]
    price = price.replace(",","")
    ds.loc[i,"Price"] =price

In [12]:
ds["Price"]

0              80000
1             425000
2      Ask For Price
3             325000
4             575000
           ...
886           300000
888           260000
889           390000
890           180000
891           160000
Name: Price, Length: 842, dtype: str

In [13]:
ds["Price"] = pd.to_numeric(ds["Price"],errors='coerce')
ds["Price"].unique()

array([  80000.,  425000.,      nan,  325000.,  575000.,  175000.,
        190000.,  830000.,  250000.,  182000.,  315000.,  415000.,
        320000., 1000000.,  500000.,  350000.,  160000.,  310000.,
         75000.,  100000.,  290000.,   95000.,  180000.,  385000.,
        105000.,  650000.,  689999.,  448000.,  549000.,  501000.,
        489999.,  280000.,  349999.,  284999.,  345000.,  499999.,
        235000.,  249999., 1475000.,  395000.,  220000.,  170000.,
         85000.,  200000.,  570000.,  110000.,  448999., 1891111.,
        159500.,  344999.,  449999.,  865000.,  699000.,  375000.,
        224999., 1200000.,  195000.,  351000.,  240000.,   90000.,
        155000.,  600000.,  189500.,  210000.,  390000.,  135000.,
       1600000.,  701000.,  265000.,  525000.,  372000.,  635000.,
        550000.,  485000.,  329500.,  251111.,  569999.,   69999.,
        299999.,  399999.,  450000.,  270000.,  158400.,  179000.,
        125000.,  299000.,  150000.,  275000.,  285000.,  340000.,
         70000.,  289999.,  849999.,  749999.,  274999.,  984999.,
        599999.,  244999.,  474999.,  245000.,  169500.,  370000.,
        168000.,  145000.,   98500.,  209000.,  185000.,  900000.,
        699999.,  199999.,  544999.,  199000.,  540000.,   49000.,
        700000.,   55000.,  895000.,  355000.,  565000.,  365000.,
         40000.,  400000.,  330000.,  580000.,  379000.,  219000.,
        519000.,  730000., 2000000., 2100000., 1400000.,  311000.,
        855000.,  535000.,  178000.,  300000.,  255000.,  549999.,
        380000.,   57000.,  410000.,  225000.,  120000.,   59000.,
        599000.,  675000.,   72500.,  610000.,  230000.,  520000.,
        524999.,  424999.,  644999.,  584999.,  799999.,  444999.,
        649999.,  944999.,  574999.,  374999.,  130000.,  401000.,
       1350000.,  174999.,  239999.,   99999.,  324999., 1074999.,
       1130000.,  149000.,  770000.,   30000.,  335000.,  399000.,
         65000.,  169999.,  165000.,  560000.,  950000.,  715000.,
         45000.,  940000.,  155555., 1500000.,  495000.,  800000.,
       1299000.,  530000., 1499000.,   32000.,  405000.,  760000.,
        750000.,  419000.,  140000., 1540000.,  123000.,  498000.,
        480000.,  488000., 1525000.,  548900.,  725000.,   99000.,
         52000., 2800000.,  499000.,  381000.,  278000.,  690000.,
        260000.,   90001.,  115000., 1599000.,  159000.,   51999.,
        215000.,   35000., 1150000.,  269000.,   60000.,  430000.,
       8500003.,  401919.,  490000.,  424000.,  205000.,  549900.,
        435000.,  189700.,  389700.,  360000.,  295000.,  114990.,
       1065000.,  470000.,   48000.,  188000.,  465000.,  179999.,
       2190000., 2390000., 1075000.,  475000., 1025000.,  615000.,
       1900000., 1490000., 1510000., 1850000.,  790000., 1725000.,
       1225000.,   68000.,  970000., 3100000.,  899000.,   88000.,
         53000.,  568500.,   71000.,  590000.,  795000.,   42000.,
        189000.,  162000.,   35999., 2900000.,   39999.,   50500.,
        510000.,  860000.,  500001.])

In [14]:
ds.dropna(subset = "Price", inplace=True)

In [15]:
ds["Price"]

0       80000.0
1      425000.0
3      325000.0
4      575000.0
6      175000.0
         ...
886    300000.0
888    260000.0
889    390000.0
890    180000.0
891    160000.0
Name: Price, Length: 819, dtype: float64

In [16]:
ds.info()

<class 'pandas.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    str
 1   company     819 non-null    str
 2   year        819 non-null    float64
 3   Price       819 non-null    float64
 4   kms_driven  819 non-null    str
 5   fuel_type   816 non-null    str
dtypes: float64(2), str(4)
memory usage: 44.8 KB

In [17]:
ds["kms_driven"].unique()

<StringArray>
[  '45,000 kms',       '40 kms',   '28,000 kms',   '36,000 kms',
   '41,000 kms',   '25,000 kms',   '24,530 kms',   '60,000 kms',
   '30,000 kms',   '32,000 kms',
 ...
   '33,400 kms',   '60,123 kms', '1,37,495 kms',   '91,200 kms',
 '1,46,000 kms', '1,00,800 kms',    '2,100 kms',    '2,500 kms',
 '1,32,000 kms',       'Petrol']
Length: 250, dtype: str

In [18]:
ds["kms_driven"] = ds["kms_driven"].str.replace(",","")

In [19]:
ds["kms_driven"] = ds["kms_driven"].str.replace("kms","")

In [20]:
ds["kms_driven"].str.strip()

0       45000
1          40
3       28000
4       36000
6       41000
        ...
886    132000
888     27000
889     40000
890    Petrol
891    Petrol
Name: kms_driven, Length: 819, dtype: str

In [21]:
ds["kms_driven"]

0       45000
1          40
3       28000
4       36000
6       41000
        ...
886    132000
888     27000
889     40000
890     Petrol
891     Petrol
Name: kms_driven, Length: 819, dtype: str

In [22]:
ds.info()

<class 'pandas.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    str
 1   company     819 non-null    str
 2   year        819 non-null    float64
 3   Price       819 non-null    float64
 4   kms_driven  819 non-null    str
 5   fuel_type   816 non-null    str
dtypes: float64(2), str(4)
memory usage: 44.8 KB

In [23]:
ds["fuel_type"].unique()

<StringArray>
['Petrol', 'Diesel', nan, 'LPG']
Length: 4, dtype: str

In [24]:
ds.dropna(subset=["fuel_type"],inplace=True)

In [25]:
ds.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    float64
 3   Price       816 non-null    float64
 4   kms_driven  816 non-null    str
 5   fuel_type   816 non-null    str
dtypes: float64(2), str(4)
memory usage: 44.6 KB

In [26]:
for i in ds.index:
    company  = ds.loc[i,"company"]
    name = ds.loc[i,"name"]
    name = name.replace(company,"")
    ds.loc[i,"name"] = name
ds["name"] = ds["name"].str.strip()
ds["name"].unique()

<StringArray>
[  'Santro Xing XO eRLX Euro III',                 'Jeep CL550 MDI',
 'Grand i10 Magna 1.2 Kappa VTVT',    'EcoSport Titanium 1.5L TDCi',
                           'Figo',                            'Eon',
    'EcoSport Ambiente 1.5L TDCi',        'Suzuki Alto K10 VXi AMT',
          'Fabia Classic 1.2 MPI',            'Suzuki Stingray VXi',
 ...
                      'Quanto C4',             'Suzuki Swift Dzire',
             'i20 Select Variant',                 'City VX Petrol',
                           'Getz',          'Benz C Class 200 K MT',
                          'Fabia',            'Suzuki Ritz VXI ABS',
           'Indica V2 DLE BS III',                 'Zest XM Diesel']
Length: 463, dtype: str

In [27]:
ds.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    float64
 3   Price       816 non-null    float64
 4   kms_driven  816 non-null    str
 5   fuel_type   816 non-null    str
dtypes: float64(2), str(4)
memory usage: 76.9 KB

In [28]:
ds.duplicated().value_counts()

False    724
True      92
Name: count, dtype: int64

In [29]:
ds.drop_duplicates(inplace=True)

In [30]:
ds.duplicated().value_counts()

False    724
Name: count, dtype: int64

In [31]:
ds["Price"].min()

np.float64(30000.0)

In [32]:
ds["Price"].max()

np.float64(8500003.0)

In [33]:
ds["kms_driven"].min()

'0 '

In [34]:
ds["kms_driven"].max()

'99000 '

In [35]:
ds.info()

<class 'pandas.DataFrame'>
Index: 724 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        724 non-null    str
 1   company     724 non-null    str
 2   year        724 non-null    float64
 3   Price       724 non-null    float64
 4   kms_driven  724 non-null    str
 5   fuel_type   724 non-null    str
dtypes: float64(2), str(4)
memory usage: 39.6 KB

In [36]:
ds["kms_driven"] = pd.to_numeric(ds["kms_driven"],errors='coerce')

In [37]:
ds.info()

<class 'pandas.DataFrame'>
Index: 724 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        724 non-null    str
 1   company     724 non-null    str
 2   year        724 non-null    float64
 3   Price       724 non-null    float64
 4   kms_driven  724 non-null    int64
 5   fuel_type   724 non-null    str
dtypes: float64(2), int64(1), str(3)
memory usage: 39.6 KB

In [38]:
ds

,name,company,year,Price,kms_driven,fuel_type
0,Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,45000,Petrol
1,Jeep CL550 MDI,Mahindra,2006.0,425000.0,40,Diesel
3,Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000,Petrol
4,EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000,Diesel
6,Figo,Ford,2012.0,175000.0,41000,Diesel
...,...,...,...,...,...,...
883,Suzuki Ritz VXI ABS,Maruti,2011.0,270000.0,50000,Petrol
885,Indica V2 DLE BS III,Tata,2009.0,110000.0,30000,Diesel
886,Corolla Altis,Toyota,2009.0,300000.0,132000,Petrol
888,Zest XM Diesel,Tata,2018.0,260000.0,27000,Diesel
889,Quanto C8,Mahindra,2013.0,390000.0,40000,Diesel

In [39]:
ds["Price"].max()

np.float64(8500003.0)

In [40]:
ds["kms_driven"].max()

np.int64(400000)

In [41]:
ds[ds["kms_driven"]<100]

,name,company,year,Price,kms_driven,fuel_type
1,Jeep CL550 MDI,Mahindra,2006.0,425000.0,40,Diesel
215,Jeep MM 550 XDB,Mahindra,2019.0,390000.0,60,Diesel
220,Jeep CL550 MDI,Mahindra,2019.0,379000.0,0,Diesel
302,Suzuki Swift VXi 1.2 ABS BS IV,Maruti,2019.0,610000.0,73,Petrol
387,Innova 2.5 E MS 7 STR BS IV,Toyota,2012.0,770000.0,0,Diesel
470,Suzuki Swift Dzire Tour VXi,Maruti,2011.0,230000.0,65,Petrol
702,Figo Petrol Titanium,Ford,2019.0,525000.0,0,Petrol
721,Suzuki Zen Estilo LXI Green CNG,Maruti,2009.0,125000.0,0,Petrol
738,Creta 1.6 SX,Hyundai,2019.0,1200000.0,0,Petrol
762,Tiago Revotorq XZ,Tata,2019.0,568500.0,0,Petrol

In [42]:
ds = ds[ds["Price"]<8500000]

In [43]:
ds["Price"].max()

np.float64(3100000.0)

In [44]:
ds = ds[ds["kms_driven"]>500]

In [45]:
ds.info()

<class 'pandas.DataFrame'>
Index: 709 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        709 non-null    str
 1   company     709 non-null    str
 2   year        709 non-null    float64
 3   Price       709 non-null    float64
 4   kms_driven  709 non-null    int64
 5   fuel_type   709 non-null    str
dtypes: float64(2), int64(1), str(3)
memory usage: 38.8 KB

In [46]:
ds.reset_index(drop=True,inplace= True)
ds

,name,company,year,Price,kms_driven,fuel_type
0,Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,45000,Petrol
1,Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000,Petrol
2,EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000,Diesel
3,Figo,Ford,2012.0,175000.0,41000,Diesel
4,Eon,Hyundai,2013.0,190000.0,25000,Petrol
...,...,...,...,...,...,...
704,Suzuki Ritz VXI ABS,Maruti,2011.0,270000.0,50000,Petrol
705,Indica V2 DLE BS III,Tata,2009.0,110000.0,30000,Diesel
706,Corolla Altis,Toyota,2009.0,300000.0,132000,Petrol
707,Zest XM Diesel,Tata,2018.0,260000.0,27000,Diesel
708,Quanto C8,Mahindra,2013.0,390000.0,40000,Diesel

In [47]:
ds["name"] = ds["name"].astype(object)
ds["company"] = ds["company"].astype(object)
ds["fuel_type"] = ds["fuel_type"].astype(object)

In [48]:
ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 709 entries, 0 to 708
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        709 non-null    object
 1   company     709 non-null    object
 2   year        709 non-null    float64
 3   Price       709 non-null    float64
 4   kms_driven  709 non-null    int64
 5   fuel_type   709 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 33.4+ KB

In [49]:
ds

,name,company,year,Price,kms_driven,fuel_type
0,Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,45000,Petrol
1,Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000,Petrol
2,EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000,Diesel
3,Figo,Ford,2012.0,175000.0,41000,Diesel
4,Eon,Hyundai,2013.0,190000.0,25000,Petrol
...,...,...,...,...,...,...
704,Suzuki Ritz VXI ABS,Maruti,2011.0,270000.0,50000,Petrol
705,Indica V2 DLE BS III,Tata,2009.0,110000.0,30000,Diesel
706,Corolla Altis,Toyota,2009.0,300000.0,132000,Petrol
707,Zest XM Diesel,Tata,2018.0,260000.0,27000,Diesel
708,Quanto C8,Mahindra,2013.0,390000.0,40000,Diesel

In [50]:
ds.isnull().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64

In [51]:
ds.reset_index(drop=True,inplace= True)
ds

,name,company,year,Price,kms_driven,fuel_type
0,Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,45000,Petrol
1,Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000,Petrol
2,EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000,Diesel
3,Figo,Ford,2012.0,175000.0,41000,Diesel
4,Eon,Hyundai,2013.0,190000.0,25000,Petrol
...,...,...,...,...,...,...
704,Suzuki Ritz VXI ABS,Maruti,2011.0,270000.0,50000,Petrol
705,Indica V2 DLE BS III,Tata,2009.0,110000.0,30000,Diesel
706,Corolla Altis,Toyota,2009.0,300000.0,132000,Petrol
707,Zest XM Diesel,Tata,2018.0,260000.0,27000,Diesel
708,Quanto C8,Mahindra,2013.0,390000.0,40000,Diesel

In [53]:
ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 709 entries, 0 to 708
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        709 non-null    object
 1   company     709 non-null    object
 2   year        709 non-null    float64
 3   Price       709 non-null    float64
 4   kms_driven  709 non-null    int64
 5   fuel_type   709 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 33.4+ KB

In [54]:
ds.to_csv("clean_data.csv")